<?php

function spoor_acht_custom_form_alter(&$form, $form_state, $form_id) { 
  if ($form_state['view']->name == 'news') {
    // Add our custom All buttons.
    $form['field_news_category_tid']['#options'] = array("-ALL-" => t("- All -")) + $form['field_news_category_tid']['#options'];
    array_unshift($form['#submit'], 'spoor_acht_custom_exposed_form_submit');
  }
}

function spoor_acht_custom_exposed_form_submit(&$form, &$form_state) { 
  if (!empty($form_state['values']['field_news_category_tid']['-ALL-'])) {
    $options = $form['field_news_category_tid']['#options'];
    unset($options['-ALL-']);
    $form_state['values']['field_news_category_tid'] = $options;
  }
}

